### ISSUE TITLE
Project service

### ISSUE THREAD

**Issue by lexusdrumgold** [flex-development/teamtasks#10]
**Task description**  
Create, retrieve, update, and remove team projects. Manage project leaders

**Subtasks**  

- [ ] `src/middleware/project.middleware.js`
- [ ] `src/constants/project.constants.js` 
- [ ] `src/hooks/project.hooks.js`
- [ ] `src/services/project.service.js`
- [ ] Unit testing

**Documentation**  
n/a
