### ISSUE TITLE
Database service

### ISSUE THREAD

**Issue by lexusdrumgold** [flex-development/teamtasks#5]
**Task description**  
Implement server authentication using Feathers

**Subtasks**  

- [ ] `src/middleware/database.middleware.js`
- [ ] `src/constants/database.constants.js` 
- [ ] `src/hooks/database.hooks.js`
- [ ] `src/services/database.service.js`
- [ ] Unit testing

**Documentation**  

- [Common Database API](https://docs.feathersjs.com/api/authentication/jwt.html#jwt-authentication)

**Related Issues** 
- [User service - #3](#3l)
