### ISSUE TITLE
Storage service

### ISSUE THREAD

**Issue by lexusdrumgold** [flex-development/teamtasks#6]
**Task description**  
Implement storage service to handle user media

**Subtasks**  

- [ ] `src/middleware/storage.middleware.js`
- [ ] `src/constants/storage.constants.js` 
- [ ] `src/hooks/storage.hooks.js`
- [ ] `src/services/storage.service.js`
- [ ] Unit testing

**Documentation**  

- [File uploads in FeathersJS](https://docs.feathersjs.com/guides/advanced/file-uploading.html)

**Related Issues** 
- [User service - #3](#3l)
