### ISSUE TITLE
Team service

### ISSUE THREAD

**Issue by lexusdrumgold** [flex-development/teamtasks#7]
**Task description**  
Create, retrieve, update, and remove teams. Handle team leaders and media. Handle team invitations. Edit member permissions

**Subtasks**  

- [ ] `src/middleware/team.middleware.js`
- [ ] `src/constants/team.constants.js` 
- [ ] `src/hooks/team.hooks.js`
- [ ] `src/services/team.service.js`
- [ ] `Member` service
- [ ] `Notification` service
- [ ] Unit testing

**Documentation**  
n/a
