### ISSUE TITLE
Member service

### ISSUE THREAD

**Issue by lexusdrumgold** [flex-development/teamtasks#8]
**Task description**  
Create, retrieve, update, and remove team members

**Subtasks**  

- [ ] `src/middleware/member.middleware.js`
- [ ] `src/constants/member.constants.js` 
- [ ] `src/hooks/member.hooks.js`
- [ ] `src/services/member.service.js`
- [ ] Unit testing

**Documentation**  
n/a

**Related Issues**  
- [Team Service - #7](#7)
