### ISSUE TITLE
Notification service

### ISSUE THREAD

**Issue by lexusdrumgold** [flex-development/teamtasks#9]
**Task description**  
Create, retrieve, update, and remove user notifications.

**Subtasks**  

- [ ] `src/middleware/notification.middleware.js`
- [ ] `src/constants/notification.constants.js` 
- [ ] `src/hooks/notification.hooks.js`
- [ ] `src/services/notification.service.js`
- [ ] Unit testing

**Documentation**  
n/a

**Related Issues**  
- [Team Service - #7](#7)
